# Generated by Django 4.1.5 on 2023-01-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_rl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrmsuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hrmsuser',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='hrmsuser',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='hrmsuser',
            name='phone',
        ),
    ]
